version: 2

workflows:
  single-node:
    steps:
      -
        name: "train_seq2seq"
        command: experiment.run_single_node
        params:
          command: bash run.sh
          container: aditya1e0/pytorch_nlp:1
          machineType: "K80"
      triggers:
        branches:
          ignore: irrelevant-branch
        tags:
          only:
            - train.*
        
